### ISSUE TITLE
Incompatible with Mail Version 10.1 (3251) (Mac OS 10.12.1)

### ISSUE THREAD

**Issue by romanrev** [fikovnik/GMailinator#7]
Plugin became incompatible again with the release of Mac OS 10.12.1, Mail Version 10.1 (3251) - I tried adding the UUID `9054AFD9-2607-489E-8E63-8B09A749BC61` to `~/Library/Mail/Bundles/GMailinator.mailbundle/Contents/Info.plist` but that did not help

**Comment by fikovnik** [comment]
try the latest master - it works for me so shall it for you

**Comment by romanrev** [comment]
Just tried rebuilding the plugin from the latest master, and still getting this:

<img width="419" alt="screenshot 2016-10-29 09 17 57" src="https://cloud.githubusercontent.com/assets/2794589/19824132/af2c6f12-9db8-11e6-9cae-9cf59d3051ad.png">

**Comment by romanrev** [comment]
Ok I figured out what the issue was: I had to add the UUID `9054AFD9-2607-489E-8E63-8B09A749BC61` to the array

```
        <key>Supported10.12PluginCompatibilityUUIDs</key>
        <array>
...
        </array>
```

instead of

```
        <key>SupportedPluginCompatibilityUUIDs</key>
        <array>
        </array>
```

**Comment by fikovnik** [comment]
Can you make PR?

**Comment by romanrev** [comment]
Done, see above
